//
//  ListLaunchesInteractor.swift
//  SpaceX
//
//  Created by Eric Granger on 08/02/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListLaunchesBusinessLogic
{
  func doSomething(request: ListLaunches.Something.Request)
}

protocol ListLaunchesDataStore
{
  //var name: String { get set }
}

class ListLaunchesInteractor: ListLaunchesBusinessLogic, ListLaunchesDataStore
{
  var presenter: ListLaunchesPresentationLogic?
  var worker: ListLaunchesWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ListLaunches.Something.Request)
  {
    worker = ListLaunchesWorker()
    worker?.doSomeWork()
    
    let response = ListLaunches.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
