//
//  ListLaunchesPresenter.swift
//  SpaceX
//
//  Created by Eric Granger on 08/02/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListLaunchesPresentationLogic
{
  func presentSomething(response: ListLaunches.Something.Response)
}

class ListLaunchesPresenter: ListLaunchesPresentationLogic
{
  weak var viewController: ListLaunchesDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ListLaunches.Something.Response)
  {
    let viewModel = ListLaunches.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
