//
//  ShowLaunchInteractor.swift
//  SpaceX
//
//  Created by Eric Granger on 08/02/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowLaunchBusinessLogic
{
  func doSomething(request: ShowLaunch.Something.Request)
}

protocol ShowLaunchDataStore
{
  //var name: String { get set }
}

class ShowLaunchInteractor: ShowLaunchBusinessLogic, ShowLaunchDataStore
{
  var presenter: ShowLaunchPresentationLogic?
  var worker: ShowLaunchWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ShowLaunch.Something.Request)
  {
    worker = ShowLaunchWorker()
    worker?.doSomeWork()
    
    let response = ShowLaunch.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
