//
//  ShowLaunchPresenter.swift
//  SpaceX
//
//  Created by Eric Granger on 08/02/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowLaunchPresentationLogic
{
  func presentSomething(response: ShowLaunch.Something.Response)
}

class ShowLaunchPresenter: ShowLaunchPresentationLogic
{
  weak var viewController: ShowLaunchDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ShowLaunch.Something.Response)
  {
    let viewModel = ShowLaunch.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
